### ISSUE TITLE
Cannot load old builds

### ISSUE THREAD

**Issue by case725** [ImaginaryDevelopment/imaginary-hero-designer#1]
Error loading old builds saying zlib1.dll is missing. Adding the library from an older version of Mid's or Pine's Hero Builder seems to have fixed this. I don't know whether that was an oversight or if that library is someone else's IP, so I won't add the file here.

**Comment by ImaginaryDevelopment** [comment]
the file should be included, I'll fix it thanks.

**Comment by case725** [comment]
No problem. Glad to help. Thanks for taking this on!
