### ISSUE TITLE
Mastermind Powersets

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [ImaginaryDevelopment/imaginary-hero-designer#20]
Dark Miasma is crashing the app. Kinetics is there, but there are no powers. I'm not sure if the remaining secondaries are messed up because of previous exceptions, or just aren't there either.

**Comment by Pine-CoH** [comment]
looks like the mastermind sets got reverted back a level :/ will fix

**Comment by ImaginaryDevelopment** [comment]
Some testing suggests it is only the Kinetic set.

**Comment by ImaginaryDevelopment** [comment]
This appears fixed
