### ISSUE TITLE
Doesn't associate .mxd files

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [ImaginaryDevelopment/imaginary-hero-designer#24]
opening a .mxd file, or even clicking one and selecting open with doesn't allow selection of the app.

Possibly a click-once installer issue?

**Comment by Metalios** [comment]
Installer issue most likely, subkeys and values need to be set in the registry for HKCU.

**Comment by ImaginaryDevelopment** [comment]
Requires admin permissions to do, but if you run the app with admin, it will now associate.
