### ISSUE TITLE
Regen Tanker - Powers Have No Effects

### ISSUE THREAD

**Issue by styopa6** [ImaginaryDevelopment/imaginary-hero-designer#27]
Steps to Reproduce:
1) New/Clear
2) Archetype: Tanker
3) Primary Power Set: Regeneration
4) Click to the Effects Tab
5) Hover over any Regeneration Power

Expected Results:
The effects of the power to be displayed

Actual Results:
Tab is empty for all powers

Addendum:
This works for Scrappers and Brutes

**Comment by ImaginaryDevelopment** [comment]
Are tankers able to select regen on a server somewhere? I thought that option wasn't present.

**Comment by Metalios** [comment]
Regen for Tankers never made it to live nor on homecoming.  - This issue can be closed

**Comment by ImaginaryDevelopment** [comment]
Either it should be fixed for theory builds, or it should be removed from the options in the db.
