### ISSUE TITLE
Warshade/Peacebringer - Flight/Teleport Pool not Valid

### ISSUE THREAD

**Issue by Hard-Eight** [ImaginaryDevelopment/imaginary-hero-designer#34]
Warshades show the Flight pool as an invalid choice. Peacebringers show the Teleport pool as an invalid choice. Homecoming removed the restriction on Warshades and Peacebringers selecting the Flight and Teleport pool respectively.

**Comment by Metalios** [comment]
This has been fixed in the latest database update
