### ISSUE TITLE
Missing Sudden Acceleration IO's

### ISSUE THREAD

**Issue by Tamorand** [ImaginaryDevelopment/imaginary-hero-designer#4]
I am only sending this regarding the missing IO's Sudden Acceleration
I am not sure if others are missing, but am sure of that.
![Sudden Acceleration](https://user-images.githubusercontent.com/50531830/59439540-13acc000-8dbb-11e9-8e78-d674a11e1a2c.jpg)

**Comment by Tamorand** [comment]
I have no idea why that pic is sideways...

**Comment by ImaginaryDevelopment** [comment]
This needs to be fixed.  Also you can edit them in using the db editor built in,  if that is helpful?

**Comment by Tamorand** [comment]
I attempted to edit the db and was unable to make the percentage changes to make them accurate.

**Comment by ImaginaryDevelopment** [comment]
which percentage changes? I've also started an attempt at getting them in, do you know where I can get the Mag numbers for it?

**Comment by Tamorand** [comment]
I'm being told by the community that it's the same MAG Numbers as Overwhelming Force IO.   Also as a side note - Shield Breaker and other Accurate Debuff IO's are not selectable for Mercenaries in the Mastermind AT.  But you can slot them in game.

**Comment by Metalios** [comment]
I have already added this complete set along with its set bonuses to the Enhancements database, just need to upload it.
