### ISSUE TITLE
installation?

### ISSUE THREAD

**Issue by manchudragon** [ImaginaryDevelopment/imaginary-hero-designer#5]
i have downloaded this  but i see no .exe files to install.  Is it just a copy and paste to the original mids/pines hero builder or what?

**Comment by ImaginaryDevelopment** [comment]
so far, yes, the plan is to fix bugs and add features eventually

**Comment by ImaginaryDevelopment** [comment]
Is this a request for an installer or just a question? If q then is it answered?

**Comment by manchudragon** [comment]
was just wondering if it was just a copy and paste add on to the current  planner or if it was its own stand alone "new" builder since i didn't see an install.exe in it.  and since its currently an addition what folder do we add this information to?

**Comment by ImaginaryDevelopment** [comment]
it's not really an addition, it's a reverse engineering of the old version.
I took it apart in such away that we can now make new copies with changes.
It does not have any new changes checked in yet.

**Comment by manchudragon** [comment]
ok so how do i install this?

**Comment by ImaginaryDevelopment** [comment]
You would download the zip and extract the files into a folder (usually
available by right clicking the zip file and selecting extract., then run
the Hero Designer.exe inside whenever you want to use it
