### ISSUE TITLE
Sentinel -> Invuln -> Durability does not allow slotting of Endurance Modification Sets

### ISSUE THREAD

**Issue by codersparks** [ImaginaryDevelopment/imaginary-hero-designer#53]
As the title says, Durability power does not allow slotting of Endurance Modification IO sets - It does allow slotting of End Mod standard IOs

Would submit a pull request to change data but don't know where the source of this is

**Comment by codersparks** [comment]
Have double checked in game and it is possible to slot those sets

**Comment by Metalios** [comment]
Thanks for the report, I'll squeeze this into 2.6.0.2 before we officially release it
