### ISSUE TITLE
MasterMind Protector Bot - Force Shield doesn't show in effects window.

### ISSUE THREAD

**Issue by SmalltalkJava** [ImaginaryDevelopment/imaginary-hero-designer#57]
MasterMind Robotics has a the Protector Bots,  a protector bot will cast a force field on the mastermind.  However it does not show up in the Effects window.  

Can Pines be updated so that the Protector Bot's force shield shows up in the effects. That way I can plan my defense slotting accordingly.  

Thank you.

**Comment by SmalltalkJava** [comment]
Here is the numbers for the Force Shield that the Protector bot casts on the MasterMind.

 -Force Shield
+7.50% strength to smashing for 4m 0s on target unresistable
+7.50% strength to lethal for 4m 0s on target unresistable
+7.50% strength to fire for 4m 0s on target unresistable 
+7.50% strength to cold for 4m 0s on target unresistable
+7.50% strength to energy for 4m 0s on target unresistable
+7.50% strength to negative energy for 4m 0s on target unresistable 
+7.50% strength to melee for 4m 0s on target unresistable
+7.50% strength to ranged for 4m 0s on target unresistable
+7.50% strength to AoE for 4m 0s on target unresistable

**Comment by Metalios** [comment]
Added in 2.6.0.3
