### ISSUE TITLE
Force Feedback: Chance for Recharge Somehow Affects Resistance Numbers

### ISSUE THREAD

**Issue by SunsetteSkye** [ImaginaryDevelopment/imaginary-hero-designer#79]
https://i.imgur.com/o5baRoQ.gifv
Video above summarizes issue. Note the view total subscreen.

**Comment by Metalios** [comment]
I am unable to reproduce this using the same IOs and powers as in the vidpic. I did notice your DB version date is different than the current. Is it possible that something was changed that is affecting this?

**Comment by SunsetteSkye** [comment]
Is there some way to update the database separately from the rest of the
program? I have just been installing updates as they come.

**Comment by Metalios** [comment]
Currently no, however we are working on a database repair option which should restore the database to database that matches the application version.

**Comment by kjbro** [comment]
I have reproduced this, and can provide a character build which does so

**Comment by kjbro** [comment]
Note:  Possibly related to #71

**Comment by Metalios** [comment]
@kjbro Can you upload the build in #help on our Discord so I can take a look?

**Comment by kjbro** [comment]
Will upload later tonight when I'm back at the computer with the build!

**Comment by Metalios** [comment]
Thank you

**Comment by Metalios** [comment]
Found the issue related to the build posted by @kjbro, it does not lay within the enhancements themselves nor the powers. It appears the Interface incarnate is applying it's affects on the caster which is what is causing the discrepancy, this would also explain why I wasn't able to replicate the issue in the original issue made by Sunsette.  I have created issue #86 regarding this
