### ISSUE TITLE
Ragnarok IOs cannot slot into Tankers Fiery Melee Breath of Fire

### ISSUE THREAD

**Issue by ann-codes** [ImaginaryDevelopment/imaginary-hero-designer#81]
I'm on Homecoming and I just discovered this today after spending the merits on Ragnaroks for my Bio/Fire Tank's Breath of Fire to find that it does not slot into the Breath of Fire though the Hero Designer allows for it.

**Comment by Metalios** [comment]
Thanks for the report

**Comment by Metalios** [comment]
@ann-codes Tested and found this to be incorrect. You can indeed slot Ragnarok very rare IO's into the power.

![image](https://user-images.githubusercontent.com/18664232/63147933-45adee80-bfc5-11e9-845d-c2ce4379d241.png)

**Comment by ann-codes** [comment]
I also just checked again and found this to be true. I'm not sure why I wasn't able to slot then (I even used 4 unslotters to get the original enhs out), but I am not able to replicate it. Thanks for checking and sorry for the trouble!
