### ISSUE TITLE
Scrapper & Brute Energy Aura - Entropic Aura - Not displaying +Recharge Properly

### ISSUE THREAD

**Issue by Seipherwood** [ImaginaryDevelopment/imaginary-hero-designer#83]
Scrapper & Brute Energy Aura's Entropic Aura gives 8.5 Recharge without enemies around (atleast at 50) but Hero Designer does not show this anywhere.

**Comment by Metalios** [comment]
This is a bug in the games power description. The power only give you a defense buff that scales up to 10 enemies, the recharge time enhancement is a flat amount which is unaffected by buffs and enhancements. You can adjust the scaling affect for the def by right clicking the power and sliding the scaling bar. Also the power does not add to your global recharge it does however reduce each abilities recharge and this is reflected already in mids. *Further testing will be done and if needed the power will be changed*

**Comment by Seipherwood** [comment]
Are you sure? In game with Energy Cloak off, it gives 8.5 Recharge with 0 enemies around, and increases by 3.5 per enemy around. Im not sure it even adds to Defense at all, except Defense Debuff, atleast on Scrapper.

**Comment by Metalios** [comment]
I will double check it as always but pretty sure.

**Comment by Seipherwood** [comment]
Atleast on the Scrapper one, it does not mention Defense anywhere on it.

https://imgur.com/vveY8Q5

**Comment by Metalios** [comment]
My mistake, I meant def debuff protection. The recharge issue has been fixed in the upcoming version
