### ISSUE TITLE
Superior Unrelenting Fury - Typos and missing 6% Fire/Cold Resist

### ISSUE THREAD

**Issue by 12thPower** [ImaginaryDevelopment/imaginary-hero-designer#84]
Superior Unrelenting Fury is supposed to have a 6% Fire/Cold resist bonus, but when 6-slotted, this bonus is not being shown in the Totals.

![io-flip](https://user-images.githubusercontent.com/11758536/63379859-2f0bec80-c363-11e9-86f9-d1fd4212bc28.gif)

There are missing commas in the tooltip for Unrelenting Fury and Superior Unrelenting Fury:

![temp-unrfury-bug](https://user-images.githubusercontent.com/11758536/63378959-4cd85200-c361-11e9-9a87-8a77b503c0af.png)

**Comment by Metalios** [comment]
Which version are you using?

**Comment by Pine-CoH** [comment]
Not sure if this was fixed earlier, but I do not see the same issue. It is providing Fire/Cold res now. As for the commas... cudos for seeing that in the wall of text...
